[build]
builder = "nixpacks"
buildCommand = "cd memory && npm install && npm run build"

[deploy]
startCommand = "cd memory && npm run railway:start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "velto-mcp-server"
type = "background"
