[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run railway:start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "velto-mcp-server"
type = "background"

[deploy.env]
NODE_ENV = "production"
