[profile.default]
src = "contracts"
out = "out"
libs = ["../lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=../lib/openzeppelin-contracts/contracts/",
    "forge-std/=../lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
